package ca.uwaterloo.gsd.ros.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptEmptyMessageContent = new ConceptDescriptorBuilder("ca.uwaterloo.gsd.ros.structure.EmptyMessageContent", MetaIdFactory.conceptId(0x73b2b904295848f1L, 0x87324d9d995324d8L, 0x2d50825385ba790L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "ca.uwaterloo.gsd.ros.structure.IElement", "com.mbeddr.core.base.structure.IEmpty").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0x73b2b904295848f1L, 0x87324d9d995324d8L, 0x2d50825385a867dL), MetaIdFactory.conceptId(0xd4280a54f6df4383L, 0xaa41d1b2bffa7eb1L, 0xe900768cf47dcc3L)).create();
  /*package*/ final ConceptDescriptor myConceptIElement = new ConceptDescriptorBuilder("ca.uwaterloo.gsd.ros.structure.IElement", MetaIdFactory.conceptId(0x73b2b904295848f1L, 0x87324d9d995324d8L, 0x2d50825385a867dL)).interface_().parents("com.mbeddr.core.base.structure.IIdentifierNamedConcept", "com.mbeddr.core.base.structure.IDocumentable").parentIds(MetaIdFactory.conceptId(0xd4280a54f6df4383L, 0xaa41d1b2bffa7eb1L, 0x617d88a37ec2f433L), MetaIdFactory.conceptId(0xd4280a54f6df4383L, 0xaa41d1b2bffa7eb1L, 0x3588b64556af2180L)).create();
  /*package*/ final ConceptDescriptor myConceptMessage = new ConceptDescriptorBuilder("ca.uwaterloo.gsd.ros.structure.Message", MetaIdFactory.conceptId(0x73b2b904295848f1L, 0x87324d9d995324d8L, 0x2d50825385a5033L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "com.mbeddr.core.base.structure.IMbeddrIDERoot", "com.mbeddr.core.base.structure.IContainerOfUniqueNames").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xd4280a54f6df4383L, 0xaa41d1b2bffa7eb1L, 0x2e7d229ef4a2cdL), MetaIdFactory.conceptId(0xd4280a54f6df4383L, 0xaa41d1b2bffa7eb1L, 0x46b83c1781e763b4L)).childDescriptors(new ConceptDescriptorBuilder.Link(1139250107225583851L, "content", MetaIdFactory.conceptId(0x73b2b904295848f1L, 0x87324d9d995324d8L, 0x2d50825385a867dL), true, true, false)).children(new String[]{"content"}, new boolean[]{true}).create();
  /*package*/ final ConceptDescriptor myConceptMessageSingleLineComment = new ConceptDescriptorBuilder("ca.uwaterloo.gsd.ros.structure.MessageSingleLineComment", MetaIdFactory.conceptId(0x73b2b904295848f1L, 0x87324d9d995324d8L, 0x4e6477385e4642ccL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "ca.uwaterloo.gsd.ros.structure.IElement").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0x73b2b904295848f1L, 0x87324d9d995324d8L, 0x2d50825385a867dL)).childDescriptors(new ConceptDescriptorBuilder.Link(6329021646629175155L, "commentPart", MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x57d533a7af15ed3bL), true, true, false)).children(new String[]{"commentPart"}, new boolean[]{true}).alias("#", "single-line comment").create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptEmptyMessageContent, myConceptIElement, myConceptMessage, myConceptMessageSingleLineComment);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0i, conceptFqName)) {
      case 0:
        return myConceptEmptyMessageContent;
      case 1:
        return myConceptIElement;
      case 2:
        return myConceptMessage;
      case 3:
        return myConceptMessageSingleLineComment;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0i = new String[]{"ca.uwaterloo.gsd.ros.structure.EmptyMessageContent", "ca.uwaterloo.gsd.ros.structure.IElement", "ca.uwaterloo.gsd.ros.structure.Message", "ca.uwaterloo.gsd.ros.structure.MessageSingleLineComment"};
}
