package ca.uwaterloo.gsd.ros.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Collections;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    {
      SAbstractConcept cncpt = ((SAbstractConcept) concept);
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x73b2b904295848f1L, 0x87324d9d995324d8L, 0x2d50825385ba790L, "ca.uwaterloo.gsd.ros.structure.EmptyMessageContent"))) {
        return Collections.<ConceptEditor>singletonList(new EmptyMessageContent_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x73b2b904295848f1L, 0x87324d9d995324d8L, 0x2d50825385a5033L, "ca.uwaterloo.gsd.ros.structure.Message"))) {
        return Collections.<ConceptEditor>singletonList(new Message_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x73b2b904295848f1L, 0x87324d9d995324d8L, 0x4e6477385e4642ccL, "ca.uwaterloo.gsd.ros.structure.MessageSingleLineComment"))) {
        return Collections.<ConceptEditor>singletonList(new MessageSingleLineComment_Editor());
      }
    }
    return Collections.<ConceptEditor>emptyList();
  }



}
