package ca.uwaterloo.gsd.ros;

/*Generated by MPS */

import jetbrains.mps.smodel.language.LanguageRuntime;
import jetbrains.mps.smodel.adapter.ids.SLanguageId;
import java.util.UUID;
import java.util.Collection;
import jetbrains.mps.generator.runtime.TemplateModule;
import jetbrains.mps.generator.runtime.TemplateUtil;
import jetbrains.mps.smodel.runtime.ILanguageAspect;
import jetbrains.mps.openapi.actions.descriptor.ActionAspectDescriptor;
import ca.uwaterloo.gsd.ros.actions.ActionAspectDescriptorImpl;
import jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsAspectDescriptor;
import jetbrains.mps.openapi.editor.descriptor.EditorAspectDescriptor;
import ca.uwaterloo.gsd.ros.editor.EditorAspectDescriptorImpl;
import jetbrains.mps.smodel.runtime.StructureAspectDescriptor;
import jetbrains.mps.text.rt.TextGenAspectDescriptor;

public class Language extends LanguageRuntime {
  public static String MODULE_REF = "73b2b904-2958-48f1-8732-4d9d995324d8(ca.uwaterloo.gsd.ros)";
  public Language() {
  }
  @Override
  public String getNamespace() {
    return "ca.uwaterloo.gsd.ros";
  }

  @Override
  public int getVersion() {
    return 0;
  }

  public SLanguageId getId() {
    return new SLanguageId(UUID.fromString("73b2b904-2958-48f1-8732-4d9d995324d8"));
  }
  @Override
  protected String[] getExtendedLanguageIDs() {
    return new String[]{"com.mbeddr.core.base"};
  }
  @Override
  public Collection<TemplateModule> getGenerators() {
    return TemplateUtil.<TemplateModule>asCollection(TemplateUtil.createInterpretedGenerator(this, "ea29e98d-b671-465a-a165-63f0254ff629(ca.uwaterloo.gsd.ros#1139250107225569088)"));
  }
  @Override
  protected <T extends ILanguageAspect> T createAspect(Class<T> aspectClass) {
    if (aspectClass == ActionAspectDescriptor.class) {
      return (T) new ActionAspectDescriptorImpl();
    }
    if (aspectClass == BehaviorAspectDescriptor.class) {
      return (T) new ca.uwaterloo.gsd.ros.behavior.BehaviorAspectDescriptor();
    }
    if (aspectClass == ConstraintsAspectDescriptor.class) {
      return (T) new ca.uwaterloo.gsd.ros.constraints.ConstraintsAspectDescriptor();
    }
    if (aspectClass == EditorAspectDescriptor.class) {
      return (T) new EditorAspectDescriptorImpl();
    }
    if (aspectClass == StructureAspectDescriptor.class) {
      return (T) new ca.uwaterloo.gsd.ros.structure.StructureAspectDescriptor();
    }
    if (aspectClass == TextGenAspectDescriptor.class) {
      return (T) new ca.uwaterloo.gsd.ros.textGen.TextGenAspectDescriptor();
    }
    return super.createAspect(aspectClass);
  }
}
