package ca.uwaterloo.gsd.ros.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class MessageSingleLineComment_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.indent();
    tgs.append("# ");
    for (SNode commentPart : SLinkOperations.getChildren(ctx.getPrimaryInput(), MetaAdapterFactory.getContainmentLink(0x73b2b904295848f1L, 0x87324d9d995324d8L, 0x4e6477385e4642ccL, 0x57d533a7af16ff73L, "commentPart"))) {
      tgs.appendNode(commentPart);
      tgs.append(" ");
    }
    tgs.newLine();
  }
}
