package ca.uwaterloo.gsd.ros.behavior;

/*Generated by MPS */

import com.mbeddr.core.base.behavior.IIdentifierNamedConcept_BehaviorDescriptor;
import com.mbeddr.core.base.behavior.IDocumentable_BehaviorDescriptor;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This interface is not involved in the actual method invocation
 */
@Deprecated
public interface IElement_BehaviorDescriptor extends IIdentifierNamedConcept_BehaviorDescriptor, IDocumentable_BehaviorDescriptor {
}
