package ca.uwaterloo.gsd.ros.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import com.mbeddr.core.base.behavior.IMbeddrIDERoot_BehaviorDescriptor;
import com.mbeddr.core.base.behavior.IContainerOfUniqueNames_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.DefaultValuesHolder;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class Message_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IMbeddrIDERoot_BehaviorDescriptor, IContainerOfUniqueNames_BehaviorDescriptor {
  public String virtual_getFqName_1213877404258(SNode __thisNode__) {
    return null;
  }
  public String virtual_getIDEDisplayString_13085436577886224(SNode __thisNode__) {
    return null;
  }
  public String virtual_getParentPopup_1707183716775892130(SNode __thisNode__) {
    return null;
  }
  public int virtual_getSortOrder_1707183716764859191(SNode __thisNode__) {
    return DefaultValuesHolder.defaultValue(Integer.TYPE);
  }
  public Iterable<SNode> virtual_getUniquelyNamedElements_5095889050031059923(SNode __thisNode__) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "ca.uwaterloo.gsd.ros.structure.Message";
  }

}
